TEZ-1832. TestSecureShuffle fails with NoClassDefFoundError: org/bouncycastle/x509/X509V1CertificateGenerator
(cherry picked from commit 49858b53c53f8931abe80876895775df48610c6f)

Conflicts:
	CHANGES.txt
	pom.xml